name: Build SyncTv

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build SyncTv
    steps:
    - uses: actions/checkout@v4
    - name: Build SyncTv
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y wget curl git gcc bash gawk gsed
          wget https://dl.google.com/go/go1.22.0.freebsd-amd64.tar.gz && tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz && rm go1.22.0.freebsd-amd64.tar.gz
          ln -s /usr/local/go/bin/go /usr/local/bin/go
        run: |
          export LATEST_APP=$(wget -qO- https://api.github.com/repos/synctv-org/synctv/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          git clone -b $LATEST_APP https://github.com/synctv-org/synctv
          cd synctv
          bash script/build.sh -M -f "gcc -static" -F "g++ -static" -p "freebsd"
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: synctv-freebsd
        path: |
            synctv/build/synctv

    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/synctv-org/synctv/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              synctv/build/synctv
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
